version: '3.8'

services:
  postgres:
    image: docker.m.daocloud.io/library/postgres:15-alpine
    container_name: bi_metadata_db
    restart: always
    environment:
      POSTGRES_USER: bi_user
      POSTGRES_PASSWORD: bi_pass
      POSTGRES_DB: bi_metadata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
